<?php

/**
 * @file
 * Primary module hooks for ims_popup_maggi module.
 */

/**
 * Preprocess function for ims_popup paragraph.
 */
function ims_popup_maggi_preprocess_paragraph__ims_popup(&$variables) {
  $variables['#attached']['library'][] = 'ims_popup_maggi/ims_popup_maggi';
}

/**
 * Preprocess function for ims_popup_block theme hook.
 */
function ims_popup_maggi_preprocess_ims_popup_block(&$variables) {
  $variables['#attached']['library'][] = 'ims_popup_maggi/ims_popup_maggi';
}
