<?php

/**
 * @file
 * IMS Popup module functionality.
 *
 * Provides popup functionality as both paragraphs and blocks.
 */

/**
 * Implements hook_theme().
 */
function ims_popup_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ims_popup' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--ims-popup',
    ],
    'ims_popup_block' => [
      'variables' => [
        'ims_popup_title' => NULL,
        'ims_popup_text' => NULL,
        'ims_popup_image' => NULL,
        'ims_popup_image_title' => NULL,
        'ims_popup_image_alt' => NULL,
        'ims_popup_logo' => NULL,
        'ims_popup_logo_title' => NULL,
        'ims_popup_logo_alt' => NULL,
        'ims_popup_link_url' => NULL,
        'ims_popup_link_text' => NULL,
        'ims_popup_link_target' => NULL,
        'ims_popup_timer' => NULL,
        'ims_popup_background' => NULL,
        'ims_popup_repeat' => NULL,
      ],
      'template' => 'ims-popup-block',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph__ims_popup().
 */
function ims_popup_preprocess_paragraph__ims_popup(&$variables) {
  $variables['#attached']['library'][] = 'ims_popup/ims_popup';
}

/**
 * Implements hook_install().
 */
function ims_popup_install() {
  \Drupal::service('config.installer')
    ->installDefaultConfig('module', 'ims_popup');
}

/**
 * Implements hook_uninstall().
 */
function ims_popup_uninstall() {
  $configs = [
    'core.entity_form_display.paragraph.ims_popup.default',
    'core.entity_view_display.paragraph.ims_popup.default',
    'field.field.paragraph.ims_popup.field_ims_popup_darken_bg',
    'field.field.paragraph.ims_popup.field_ims_popup_image',
    'field.field.paragraph.ims_popup.field_ims_popup_link',
    'field.field.paragraph.ims_popup.field_ims_popup_logo',
    'field.field.paragraph.ims_popup.field_ims_popup_repeat',
    'field.field.paragraph.ims_popup.field_ims_popup_text',
    'field.field.paragraph.ims_popup.field_ims_popup_timer',
    'field.field.paragraph.ims_popup.field_ims_popup_title',
    'field.storage.paragraph.field_ims_popup_darken_bg',
    'field.storage.paragraph.field_ims_popup_image',
    'field.storage.paragraph.field_ims_popup_link',
    'field.storage.paragraph.field_ims_popup_logo',
    'field.storage.paragraph.field_ims_popup_repeat',
    'field.storage.paragraph.field_ims_popup_text',
    'field.storage.paragraph.field_ims_popup_timer',
    'field.storage.paragraph.field_ims_popup_title',
    'paragraphs.paragraphs_type.ims_popup',
  ];

  foreach ($configs as $config_name) {
    $config = \Drupal::configFactory()->getEditable($config_name);
    if (\Drupal::configFactory()->get($config_name)->get('id')) {
      $config->delete();
    }
  }
}
