<?php

/**
 * @file
 * IMS Popup module functionality.
 *
 * Provides popup functionality as both paragraphs and blocks.
 */

/**
 * Implements hook_theme().
 */
function ims_popup_theme($existing, $type, $theme, $path) {
  return [
    'ims_popup_layout' => [
      'variables' => [
        'timer' => 0,
        'repeat' => 1,
        'background' => NULL,
        'logo' => NULL,
        'image' => NULL,
        'title' => NULL,
        'text' => NULL,
        'link_url' => NULL,
        'link_text' => NULL,
        'link_target' => NULL,
        'link_render' => NULL,
      ],
      'template' => 'ims-popup-layout',
      'path' => $path . '/templates',
    ],
    'ims_popup_block' => [
      'variables' => [
        'ims_popup_title' => NULL,
        'ims_popup_text' => NULL,
        'ims_popup_image' => NULL,
        'ims_popup_image_title' => NULL,
        'ims_popup_image_alt' => NULL,
        'ims_popup_logo' => NULL,
        'ims_popup_logo_title' => NULL,
        'ims_popup_logo_alt' => NULL,
        'ims_popup_link_url' => NULL,
        'ims_popup_link_text' => NULL,
        'ims_popup_link_target' => NULL,
        'ims_popup_timer' => NULL,
        'ims_popup_background' => NULL,
        'ims_popup_repeat' => NULL,
      ],
      'template' => 'ims-popup-block',
      'path' => $path . '/templates',
    ],
  ];
}




