<?php

/**
 * @file
 * Primary module hooks for ims_popup_buitoni module.
 */

/**
 * File Doc Comment.
 */
function ims_popup_buitoni_preprocess_paragraph__ims_popup(&$variables) {
  $variables['#attached']['library'][] = 'ims_popup_buitoni/ims_popup_buitoni';
}

/**
 * Preprocess function for ims_popup_block theme hook.
 */
function ims_popup_buitoni_preprocess_ims_popup_block(&$variables) {
  $variables['#attached']['library'][] = 'ims_popup_buitoni/ims_popup_buitoni';
}